

services:
  backend:
    build:
      context: ./NodeBackend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - JWT_SECRET=abcdsecret 
      - DATABASE_URL=prisma+postgres://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiMDFKWjhIQ01SUEFCVEVGVFRKMzBZWjhWOFEiLCJ0ZW5hbnRfaWQiOiI2MTJhMmRkMGE0ODc0OTFhOWI0MDFjYTdlZDUzNWZiYjUyMTEwNTUwNDAxMTFlMjkzNWE1OWZjNGY5YmM5NDcwIiwiaW50ZXJuYWxfc2VjcmV0IjoiMWVhZDIxZTQtNzM3Mi00MDAwLWIwOTQtY2NjODdhZWZmMjk0In0.7PgdRWZILsIG_17Yjhba2IKwKIomPUfxSjpKGKjChvU
    depends_on:
      - frontend
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    environment:
      - VITE_API_BASE_URL=https://deploy-project-2-hgpy.onrender.com
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
